version: '3.7'

services:
  web:
    restart: always
    build: ../FlashcardApp
    command: gunicorn FlashcardApp.wsgi:application -w 2 -b :8000 --reload
    volumes:
      - ../FlashcardApp/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
